# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01af1537badfa87d962c595b20d763f5cc0b79fd37dac9256f836d2ed9469190e2cdd05d293fba08491e16c7fabdd588b90cba852a5815fca9cd7a65e3a0cb88

test:
  secret_key_base: 50dcd1b38ce4a75e9d44f9b9c61d016d97ec420e23afb28ca87149cf06f963029606282faa3845811a51afbce12e48df90ff5e456b7891a03edbb1be133edd96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
